name: odoc

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          dune-cache: true
          ocaml-compiler: "5.x"

      - run: opam install . --deps-only --with-doc
        shell: bash
      - run: opam depext --install odoc
        shell: bash
      - run: opam exec -- dune build @doc
        shell: bash
      - name: Deploy odoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: "_build/default/_doc/_html"
          destination_dir: ""

