name: odoc

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  deploy-doc:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          dune-cache: true
          ocaml-compiler: "5.x"

      - run: opam install . --deps-only --with-test --with-doc
        shell: bash
      - run: opam depext --install odoc
        shell: bash
      - run: opam exec -- dune build @doc
        shell: bash

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '_build/default/_doc/_html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
